apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "base-project-limit" 
spec:
  limits:
    - type: "Container"
      default:
        cpu: "200m" 
        memory: "512Mi" 
      defaultRequest:
        cpu: "50m" 
        memory: "128Mi"

